import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import ts from 'typescript'
const compile = async path => import('data:text/javascript;base64,' + Buffer.from(ts.transpileModule(await readFile(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64'))
const {priceLabel,relatedProducts,whatsappUrl,safeHref}=await compile('../src/domain/helpers.ts')
const {seed}=await compile('../src/data/seed.ts')
const {migrateHome}=await compile('../src/data/homeLayout.ts')
test('home migration preserves catalog, creates three hero cards and three custom images, and is idempotent',()=>{const original=structuredClone(seed);original.products[0].name='Edición conservada';const result=migrateHome(original);assert.equal(result.products[0].name,'Edición conservada');const hero=result.blocks.find(b=>b.type==='hero');assert.equal(hero.slides.length,3);assert.equal(hero.slides[0].title,original.blocks[0].title);assert.equal(hero.slides[1].href,'/categoria/impresion-3d');const banner=result.blocks.find(b=>b.type==='banner');assert.equal(banner.gallery.length,3);assert.match(banner.whatsappMessage,/personalizada/);assert.equal(result.blocks.filter(b=>b.type==='product-carousel'&&b.categoryId==='impresion-3d').length,1);assert.deepEqual(migrateHome(result),result);assert.equal(original.layoutRevision,undefined)})
test('related products exclude current, drafts and other categories; deduplicate manual picks',()=>{const p={...seed.products[0],relatedIds:['demo-0','demo-4','demo-1','demo-1','demo-2']};const all=seed.products.map(x=>x.id==='demo-2'?{...x,status:'draft'}:x);assert.deepEqual(relatedProducts(p,all).map(x=>x.id),['demo-1'])})
test('null prices are quotes, unavailable prices do not lower the advertised price',()=>{const p=structuredClone(seed.products[0]);p.variants[0].priceCents=null;p.variants[1].availability='unavailable';assert.equal(priceLabel(p),'Por cotizar');p.variants[0].priceCents=10000;assert.equal(priceLabel(p),'$100.00')})
test('WhatsApp validates quantity/availability and encodes selected variation subtotal',()=>{const p=seed.products[4],v=p.variants[1];assert.equal(whatsappUrl('',p,v,1,'','https://example.test'),null);assert.equal(whatsappUrl('525500000000',p,v,0,'','https://example.test'),null);assert.equal(whatsappUrl('525500000000',p,{...v,availability:'unavailable'},1,'','https://example.test'),null);const result=new URL(whatsappUrl('525500000000',p,v,2,'Ana & Luis','https://example.test'));const message=result.searchParams.get('text');assert.match(message,/Negro/);assert.match(message,/720\.00/);assert.match(message,/Ana & Luis/);assert.match(message,/Envío por cotizar/)})
test('links reject script and protocol relative destinations',()=>{assert.equal(safeHref('javascript:alert(1)'),'');assert.equal(safeHref('//example.test'),'');assert.equal(safeHref('/categoria/maquillaje'),'/categoria/maquillaje')})
