import { useEffect, useRef, useState } from 'react'
import { Link, NavLink, Route, Routes, useLocation, useParams } from 'react-router-dom'
import { categories, type HomeBlock, type Product } from './domain/catalog'
import { money, priceLabel, relatedProducts, safeHref, variantLabel, whatsappUrl } from './domain/helpers'
import { StoreProvider, useStore } from './data/Store'
import { Admin } from './pages/Admin'
import { HeroBanner, CustomBanner } from './components/HomeBanners'
import { mascotIcons } from './data/homeLayout'
import { AssetImage } from './components/AssetImage'
import { ProductGallery } from './components/ProductGallery'
export function ProductImage({ product, index = 0 }: { product: Product; index?: number }) { const src=product.images[index]; const [failed,setFailed]=useState(false); useEffect(()=>setFailed(false),[src?.url]); return src && !failed ? <AssetImage src={src.url} alt={src.alt || product.name} loading="lazy" onError={()=>setFailed(true)}/> : <div className={`image-empty ${product.categoryId}`}><span>{product.categoryId==='maquillaje'?'COLOR /':'FORMA /'}</span><strong>{product.name}</strong><small>Fotografía pendiente</small></div> }
export function ProductCard({product}:{product:Product}) { return <Link className="product-card" to={`/producto/${product.slug}`}><div className="product-image"><ProductImage product={product}/><span className="product-tag">{product.categoryId==='maquillaje'?'Maquillaje':'Impresión 3D'}</span></div><div className="product-caption"><h3>{product.name}</h3><span>↗</span></div><p>{priceLabel(product)} <small>MXN</small></p></Link> }
function Carousel({title,text,products}:{title:string;text?:string;products:Product[]}) { const rail=useRef<HTMLDivElement>(null); if(!products.length)return null; return <section className="section"><div className="section-head"><div><p className="eyebrow">LA SELECCIÓN</p><h2>{title}</h2>{text&&<p>{text}</p>}</div><div className="arrows"><button aria-label="Productos anteriores" onClick={()=>rail.current?.scrollBy({left:-350,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}>←</button><button aria-label="Más productos" onClick={()=>rail.current?.scrollBy({left:350,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}>→</button></div></div><div className="product-rail" ref={rail}>{products.map(p=><ProductCard key={p.id} product={p}/>)}</div></section> }
function Block({block:b}:{block:HomeBlock}) { const {data}=useStore(); const all=data.products.filter(p=>p.status==='published'); if(b.type==='product-carousel'){ const products=b.productIds.length?b.productIds.map(id=>all.find(p=>p.id===id)).filter((p):p is Product=>!!p):all.filter(p=>!b.categoryId||p.categoryId===b.categoryId).sort((a,b)=>a.order-b.order); return <Carousel title={b.title} text={b.text} products={products}/> }
 if(b.type==='cards')return <section className="section"><h2>{b.title}</h2><div className="info-grid">{b.cards.map((c,i)=>{const p=all.find(p=>p.id===c.productId); if(c.productId&&!p)return null; return p?<ProductCard key={i} product={p}/>:<article className="info-card" key={i}><img className="mascot-icon" src={mascotIcons[i%3]} alt="" loading="lazy"/><h3>{c.title}</h3><p>{c.text}</p>{safeHref(c.href)&&<Link to={safeHref(c.href)}>Descubrir ↗</Link>}</article>})}</div></section>
 return b.type==='hero'?<HeroBanner block={b}/>:<CustomBanner block={b} phone={data.settings.whatsapp}/>
}
function Home(){const {data}=useStore();return <><h1 className="sr-only">{data.settings.name}: maquillaje e impresión 3D</h1>{data.blocks.filter(b=>b.visible).sort((a,b)=>a.order-b.order).map(b=><Block key={b.id} block={b}/>)}<div className="category-links">{categories.map(c=><Link key={c.id} to={`/categoria/${c.id}`}>{c.name}<span>Ver colección ↗</span></Link>)}</div></>}
function Category(){const {categoryId}=useParams();const {data}=useStore();const [limit,setLimit]=useState(12);useEffect(()=>setLimit(12),[categoryId]);const category=categories.find(c=>c.id===categoryId);if(!category)return <NotFound/>;const products=data.products.filter(p=>p.categoryId===categoryId&&p.status==='published').sort((a,b)=>a.order-b.order);return <section className="section"><div className="breadcrumbs"><Link to="/">Inicio</Link> / {category.name}</div><div className="collection-heading"><div><p className="eyebrow">LA COLECCIÓN</p><h1>{category.name}</h1></div><p>{products.length} productos</p></div>{products.length?<><div className="product-grid">{products.slice(0,limit).map(p=><ProductCard key={p.id} product={p}/>)}</div>{products.length>limit&&<button className="button load" onClick={()=>setLimit(limit+12)}>Cargar más productos</button>}</>:<div className="empty"><h2>Esta colección está en preparación</h2><Link to="/">Explorar novedades</Link></div>}</section>}
function ProductPage(){const {slug}=useParams();const {data}=useStore();const p=data.products.find(p=>p.slug===slug&&p.status==='published');return p?<ProductDetail key={p.id} product={p}/>:<NotFound/>}
function ProductDetail({product:p}:{product:Product}){const {data}=useStore();const [selected,setSelected]=useState(p.variants.find(v=>v.availability!=='unavailable')?.id||'');const [quantity,setQuantity]=useState(1);const [note,setNote]=useState('');const variant=p.variants.find(v=>v.id===selected);const url=variant?whatsappUrl(data.settings.whatsapp,p,variant,quantity,note,window.location.href):null;return <><div className="breadcrumbs"><Link to="/">Inicio</Link> / <Link to={`/categoria/${p.categoryId}`}>{categories.find(c=>c.id===p.categoryId)?.name}</Link> / {p.name}</div><section className="pdp"><ProductGallery product={p}/><div className="pdp-copy"><p className="eyebrow">{categories.find(c=>c.id===p.categoryId)?.name}</p><h1>{p.name}</h1><p className="pdp-price">{variant?.priceCents!=null?money(variant.priceCents):'Por cotizar'} <small>MXN</small></p><p className="muted">Envío por cotizar</p><p className="description">{p.description}</p><fieldset><legend>Elige tu opción</legend><div className="variants">{p.variants.map(v=><button key={v.id} disabled={v.availability==='unavailable'} className={selected===v.id?'selected':''} aria-pressed={selected===v.id} onClick={()=>setSelected(v.id)}>{variantLabel(v)}{v.availability==='unavailable'?' · No disponible':''}</button>)}</div></fieldset><label>Cantidad<input type="number" min="1" max="99" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label>{p.personalizationAllowed&&<label>Cuéntanos tu idea (opcional)<textarea value={note} maxLength={500} onChange={e=>setNote(e.target.value)} placeholder="Nombre, medidas o detalles de personalización"/></label>}{variant?.availability==='made-to-order'&&<p className="availability">Fabricación bajo pedido · {p.leadTime||'Plazo por confirmar'}</p>}{url?<a className="button whatsapp" href={url} target="_blank" rel="noreferrer">Solicitar por WhatsApp ↗</a>:<><button className="button" disabled>Consulta no disponible</button><p className="muted">{!data.settings.whatsapp?'El número de contacto aún no está configurado.':'Selecciona una opción disponible y una cantidad de 1 a 99.'}</p></>}<p className="small">Confirmaremos disponibilidad, precio final y envío por mensaje. Esta solicitud no confirma un pedido.</p></div></section><Carousel title="Más de esta colección" products={relatedProducts(p,data.products)}/></>}
function NotFound(){return <section className="empty"><p className="eyebrow">404</p><h1>No encontramos este producto o página</h1><Link className="button" to="/">Volver al inicio</Link></section>}
function Shell(){const {data,remote,loading,error}=useStore();const location=useLocation();useEffect(()=>{window.scrollTo(0,0);const p=data.products.find(p=>`/producto/${p.slug}`===location.pathname&&p.status==='published');const c=categories.find(c=>`/categoria/${c.id}`===location.pathname);document.title=`${p?.name||c?.name||(location.pathname==='/admin'?'Administración':'Maquillaje e impresión 3D')} | ${data.settings.name}`},[location.pathname,data]);return <><a className="skip" href="#content">Saltar al contenido</a>{!remote&&<div className="demo-bar">Demostración · Datos locales en este navegador · Google sin conectar</div>}<div className="announcement">{data.settings.announcement}</div><header><Link className="brand" to="/" aria-label="Ninaru 3D, inicio"><span className="brand-logo" role="img" aria-label="Ninaru 3D" /></Link><nav aria-label="Navegación principal"><NavLink to="/" end>Inicio</NavLink>{categories.map(c=><NavLink key={c.id} to={`/categoria/${c.id}`}>{c.name}</NavLink>)}</nav></header><main id="content">{location.pathname!=='/admin'&&loading?<section className="empty" role="status">Cargando catálogo…</section>:location.pathname!=='/admin'&&error?<section className="empty" role="alert"><h1>No pudimos cargar el catálogo</h1><p>{error}</p><button onClick={()=>window.location.reload()}>Reintentar</button></section>:<Routes><Route path="/" element={<Home/>}/><Route path="/categoria/:categoryId" element={<Category/>}/><Route path="/producto/:slug" element={<ProductPage/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<NotFound/>}/></Routes>}</main><footer><Link className="brand" to="/" aria-label="Ninaru 3D, inicio"><span className="brand-logo" role="img" aria-label="Ninaru 3D" /></Link><p>Maquillaje e impresión 3D.<br/>Encuentra algo que hable de ti.</p><div>{categories.map(c=><Link key={c.id} to={`/categoria/${c.id}`}>{c.name}</Link>)}</div><small>Precios en MXN · Envío por cotizar</small></footer></>}
export function App(){return <StoreProvider><Shell/></StoreProvider>}
